Change cc compile prompt to include the header

diff --git a/DockerFileFolder/Dockerfile b/DockerFileFolder/Dockerfile
--- a/DockerFileFolder/Dockerfile
+++ b/DockerFileFolder/Dockerfile
@@ -1,17 +1,20 @@
-#Use gcc compiler for C
+# Use gcc compiler for C
 FROM gcc:latest
 
-#Set the working directory
+# Set the working directory
 WORKDIR /usr/src/printf
 
-#Copy header files from the 'inc' directory
+# Copy header files from the 'inc' directory
 COPY inc ./inc
 
-#Copy source files from the 'src' directory
+# Copy source files from the 'src' directory
 COPY src ./src
 
-#Compile the C source files using 'cc' with specified tags
-RUN cc -Wall -Wextra -Werror -o printf ./src/*.c
+# Verify if 'cc' available
+RUN which cc || echo "cc not found"
 
-#Define the command to run the executable
+# Compile the C source files using 'cc' with specified tags
+RUN cc -Wall -Wextra -Werror -o printf ./src/*.c -I ./inc
+
+# Define the command to run the executable
 CMD ["./printf"]
